---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Al migrar datos de almacenamiento, los backends de almacenamiento se incorporan manualmente mediante API REST.  Al migrar datos del proveedor VASA, los datos se exportan desde la base de datos Derby existente y se importan a la base de datos MongoDB. 
---
= Migrar el proveedor VASA y actualizar el SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga los pasos de esta sección para migrar el proveedor VASA de las ONTAP tools for VMware vSphere 9.xx a las ONTAP tools for VMware vSphere 10.4 y actualizar el adaptador de replicación de almacenamiento (SRA) en el dispositivo VMware Live Site Recovery.



== Pasos para migrar el proveedor VASA

. Para habilitar Derby PORT 1527 en las ONTAP tools for VMware vSphere, habilite el usuario root e inicie sesión en la CLI a través de SSH.  Luego, ejecute el siguiente comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implementar OVA para ONTAP tools for VMware vSphere 10.4.
. Agregue la instancia de vCenter Server que desea migrar a las ONTAP tools for VMware vSphere 10.4. Consulte link:../configure/add-vcenter.html["Agregar una instancia de vCenter Server"] Para más información.
. Incorpore el backend de almacenamiento localmente desde las API de vCenter Server para el complemento de herramientas de ONTAP . Consultelink:../configure/add-storage-backend.html["Agregue un backend de almacenamiento mediante la interfaz del cliente vSphere"] Para más información.
. Obtenga un token de acceso para autenticar solicitudes de API REST. Utilice el siguiente ejemplo, reemplazando las variables con valores específicos de su entorno.
+
+



[listing]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
Copie y guarde el token de acceso devuelto en la respuesta. . Emita la siguiente API desde Swagger o en Postman para migrar.

+

[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+ Puedes acceder a Swagger a través de esta URL: `\https://$FQDN_IP_PORT/`, Por ejemplo: `\https://10.67.25.33:8443/`.

+

[]
====
*Método y punto final HTTP*

Esta llamada a la API REST utiliza el siguiente método y punto de conexión.

|===


| *Método HTTP* | *Camino* 


| CORREO | /api/v1 
|===
*Tipo de procesamiento*

Asincrónico

*Ejemplo de rizo*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
Cuerpo de la solicitud para otra migración de versión:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*Ejemplo de salida JSON*

El sistema devuelve un objeto de trabajo. Guarde el identificador de trabajo para usarlo en el siguiente paso.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Utilice la siguiente URI en Swagger para comprobar el estado:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
Una vez finalizado el trabajo, revise el informe de migración en la respuesta del trabajo.

. Agregue las ONTAP tools for VMware vSphere al vCenter Server.
. Registre el proveedor VASA con ONTAP tools for VMware vSphere. Para obtener instrucciones, consultelink:../configure/registration-process.html["Registrar al proveedor de VASA"] .
. Después del registro, verifique el nombre del proveedor VASA y su estado en el cliente vSphere en *Proveedores de almacenamiento*. El proveedor de VASA debería aparecer en línea, confirmando el registro exitoso.
. link:../manage/enable-services.html["Habilitar proveedor VASA"]Servicio en ONTAP tools for VMware vSphere 10.4.
. Detenga el servicio del proveedor VASA de las ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 mediante estos pasos:
+
.. En las herramientas ONTAP 9.x, abra la consola web.
.. Acceda a la consola de mantenimiento.
.. Ingresar `1` para seleccionar el menú *Configuración de la aplicación*.
.. Ingresar `5` para detener los servicios del Proveedor VASA y SRA.
.. En vSphere Client, navegue a *Inventario* > *Proveedores de almacenamiento*.
.. Seleccione el proveedor VASA de ONTAP tools 9.x desde el backend de almacenamiento y haga clic en *Eliminar*.
+
Tras detener el antiguo proveedor VASA, vCenter Server conmuta por error a las ONTAP tools for VMware vSphere. Todos los almacenes de datos y máquinas virtuales se vuelven accesibles y se sirven desde las ONTAP tools for VMware vSphere.



. Los almacenes de datos NFS y VMFS migrados aparecen en las ONTAP tools for VMware vSphere 10.4 después del trabajo de descubrimiento del almacén de datos, que puede demorar hasta 30 minutos. Compruebe su visibilidad en la página de descripción general.
. Realice la migración del parche utilizando la siguiente API en Swagger o en Postman:
+
[]
====
*Método y punto final HTTP*

Esta llamada a la API REST utiliza el siguiente método y punto de conexión.

|===


| *Método HTTP* | *Camino* 


| PARCHE | /api/v1 
|===
*Tipo de procesamiento*

Asincrónico

Utilice la siguiente URI en Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Ejemplo de rizo*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*Ejemplo de salida JSON*

Se devuelve un objeto de trabajo.  Debes guardar el identificador del trabajo para usarlo en el siguiente paso.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
El cuerpo de la solicitud está vacío para la operación de parche.




NOTE: UUID es el UUID de migración devuelto en respuesta a la API posterior a la migración.

Después de ejecutar la API de migración de parches, todas las máquinas virtuales cumplen con la política de almacenamiento.

.¿Qué sigue?
Después de completar la migración y registrar las herramientas ONTAP 10.4 en vCenter Server, siga estos pasos:

* Espere a que se complete el *Descubrimiento* y el sistema actualice los certificados automáticamente en todos los hosts.
* Espere antes de iniciar las operaciones del almacén de datos y de la máquina virtual. El tiempo de espera depende de la cantidad de hosts, almacenes de datos y máquinas virtuales. Si no esperas, es posible que veas fallos ocasionales.


Después de la actualización, si el estado de cumplimiento de la máquina virtual está desactualizado, vuelva a aplicar la política de almacenamiento siguiendo estos pasos:

. Vaya al almacén de datos y seleccione *Resumen* > *Políticas de almacenamiento de VM*.
+
El sistema muestra el estado de cumplimiento en *Cumplimiento de la política de almacenamiento de VM* como *Desactualizado*.

. Seleccione la política de VM de almacenamiento y la VM correspondiente.
. Seleccione *Aplicar*.
+
El estado de cumplimiento bajo *Cumplimiento de la política de almacenamiento de VM* se muestra como compatible. Información relacionada

+
** link:../concepts/rbac-learn-about.html["Obtenga más información sobre las ONTAP tools for VMware vSphere 10 RBAC"]
** link:../upgrade/upgrade-ontap-tools.html["Actualización de las ONTAP tools for VMware vSphere 10.x a 10.4"]






== Pasos para actualizar el adaptador de replicación de almacenamiento (SRA)

.Antes de empezar
En el plan de recuperación, el sitio protegido se refiere a la ubicación donde se ejecutan las máquinas virtuales, mientras que el sitio de recuperación es donde se recuperarán. La interfaz de SRM muestra el estado del plan de recuperación con detalles sobre los sitios protegidos y de recuperación. En el plan de recuperación, los botones *CleanupP* y *Reprotect* están deshabilitados, mientras que los botones TEST y RUN permanecen habilitados. Esto indica que el sitio está preparado para la recuperación de datos. Antes de migrar el SRA, verifique que un sitio esté en estado protegido y el otro en estado de recuperación.


NOTE: No comience la migración si se ha completado la conmutación por error pero la nueva protección está pendiente. Asegúrese de que el proceso de re-protección se haya completado antes de continuar con la migración. Si hay una conmutación por error de prueba en curso, limpie la conmutación por error de prueba e inicie la migración.

. Siga estos pasos para eliminar el adaptador SRA de herramientas ONTAP para VMware vSphere 9.xx en VMware Site Recovery:
+
.. Vaya a la página de administración de configuración de VMware Live Site Recovery
.. Vaya a la sección *Adaptador de replicación de almacenamiento*.
.. Desde el menú de puntos suspensivos seleccione *Restablecer configuración*.
.. Desde el menú de puntos suspensivos seleccione *Eliminar*.


. Realice estos pasos en los sitios de protección y recuperación.
+
.. link:../manage/enable-services.html["Habilitar ONTAP tools for VMware vSphere"]
.. Instale las ONTAP tools for VMware vSphere 10.4 SRA siguiendo los pasos que se indican enlink:../protect/configure-on-srm-appliance.html["Configurar SRA en el dispositivo VMware Live Site Recovery"] .
.. En la página de la interfaz de usuario de VMware Live Site Recovery, realice las operaciones *Descubrir matrices* y *Descubrir dispositivos* y confirme que los dispositivos se muestran como antes de la migración.



