---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Antes de implementar las ONTAP tools for VMware vSphere, debe familiarizarse con los requisitos de espacio para el paquete de implementación y algunos requisitos básicos del sistema host. 
---
= Requisitos y límites de configuración de las ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implementar las ONTAP tools for VMware vSphere, debe familiarizarse con los requisitos de espacio para el paquete de implementación y algunos requisitos básicos del sistema host.

Puede utilizar ONTAP tools for VMware vSphere con VMware vCenter Server Virtual Appliance (vCSA).  Debe implementar ONTAP tools for VMware vSphere en un cliente vSphere compatible que incluya el sistema ESXi.



== Requisitos del sistema

* *Requisitos de espacio del paquete de instalación por nodo*
+
** 15 GB para instalaciones con aprovisionamiento ligero
** 348 GB para instalaciones con aprovisionamiento grueso


* *Requisitos de tamaño del sistema host* La memoria recomendada según el tamaño de la implementación se muestra en la siguiente tabla.  Para implementar alta disponibilidad (HA), necesitará tres veces el tamaño del dispositivo especificado en la tabla.


|===


| *Tipo de despliegue* | *CPU por nodo* | *Memoria (GB) por nodo* | *Espacio en disco (GB) aprovisionado en grueso por nodo* 


| Pequeño | 9 | 18 | 350 


| Medio | 13 | 26 | 350 


| NOTA grande: La implementación grande es solo para configuración de alta disponibilidad. | 17 | 34 | 350 
|===

NOTE: Cuando la copia de seguridad está habilitada, cada clúster de herramientas ONTAP necesita otros 50 GB de espacio en el almacén de datos donde se implementan las máquinas virtuales.  Por lo tanto, la modalidad sin alta disponibilidad requiere 400 GB, y la modalidad con alta disponibilidad requiere 1100 GB de espacio en total.



== Requisitos mínimos de almacenamiento y aplicación

|===
| Almacenamiento, host y aplicaciones | Requisitos de versión 


| ONTAP | 9.14.1, 9.15.1, 9.16.0, 9.16.1 y 9.16.1P3 FAS, ASA Serie A, ASA Serie C, AFF Serie A, AFF Serie C y ASA r2. 


| Hosts ESXi compatibles con herramientas ONTAP | 7.0.3 en adelante 


| Herramientas ONTAP compatibles con vCenter Server | 7.0U3 en adelante 


| Proveedor de VASA | 3,0 


| Solicitud OVA | 10,4 


| Host ESXi para implementar la máquina virtual de herramientas ONTAP | 7.0U3 y 8.0U3 


| vCenter Server para implementar la máquina virtual de herramientas ONTAP | 7.0 y 8.0 
|===

NOTE: A partir de las ONTAP tools for VMware vSphere 10.4, el hardware de la máquina virtual cambia de la versión 10 a la 17.

La herramienta Matriz de interoperabilidad (IMT) contiene la información más reciente sobre las versiones compatibles de ONTAP, vCenter Server, hosts ESXi y aplicaciones complementarias.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^]



== Requisitos del puerto

La siguiente tabla describe los puertos de red que utiliza NetApp y sus funciones. Existen tres tipos diferentes de puertos:

* Puertos externos: Estos puertos son accesibles desde fuera del clúster o nodo de Kubernetes.  Permiten que los servicios se comuniquen con redes o usuarios externos, posibilitando la integración con sistemas fuera del entorno del clúster.
* Puertos entre nodos: Estos puertos permiten la comunicación entre nodos dentro del clúster de Kubernetes.  Son necesarios para tareas de clúster como compartir datos y trabajar juntos.  Para implementaciones de un solo nodo, los puertos entre nodos se utilizan únicamente dentro del nodo y no necesitan acceso externo.  Los puertos entre nodos pueden aceptar tráfico procedente de fuera del clúster.  Bloquee el acceso a internet de los puertos entre nodos mediante reglas de firewall.
* Puertos internos: Estos puertos se comunican dentro del clúster de Kubernetes utilizando direcciones ClusterIP.  No están expuestos externamente y no es necesario agregarlos a las reglas del firewall.



NOTE: Asegúrese de que todos los nodos de herramientas ONTAP residan en la misma subred para mantener una comunicación ininterrumpida entre sí.


|===
| *Nombre del servicio/componente* | *Puerto* | *Protocolo* | *Tipo de puerto* | *Descripción* 


| ntv-gateway-sv (LB) | 443, 8443 | TCP | Externo | Puerto de paso para la comunicación entrante del servicio VASA Provider. El certificado autofirmado del proveedor VASA y el certificado CA personalizado están alojados en este puerto. 


| SSH | 22 | TCP | Externo | Secure Shell para el inicio de sesión en servidores remotos y la ejecución de comandos. 


| Servidor rke2 | 9345 | TCP | Internodo | API de supervisor RKE2 (Restringir a redes de confianza). 


| kube-apiserver | 6443 | TCP | Internodo | Puerto del servidor de la API de Kubernetes (Restringir a redes de confianza). 


| rpcbind/asignador de puertos | 111 | TCP/UDP | Internodo | Se utiliza para la comunicación RPC entre servicios. 


| núcleos de DNS (DNS) | 53 | TCP/UDP | Internodo | Servicio de Sistema de Nombres de Dominio (DNS) para la resolución de nombres dentro del clúster. 


| NTP | 123 | UDP | Internodo | Protocolo de tiempo de red (NTP) para la sincronización horaria. 


| etcd | 2379, 2380, 2381 | TCP | Internodo | Almacén de clave-valor para datos de clúster. 


| kube-vip | 2112 | TCP | Internodo | Puerto del servidor de la API de Kubernetes. 


| kubelet | 10248, 10250 | TCP | Internodo | componente de Kubernetes 


| controlador kube | 10257 | TCP | Internodo | componente de Kubernetes 


| controlador de la nube | 10258 | TCP | Internodo | componente de Kubernetes 


| Programador de kube | 10259 | TCP | Internodo | componente de Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Internodo | componente de Kubernetes 


| calicó-nodo | 9091, 9099 | TCP | Internodo | Componente de red Calico. 


| contenedor | 10010 | TCP | Internodo | Servicio de demonio de contenedor. 


| VXLAN (Franela) | 8472 | UDP | Internodo | Red superpuesta para la comunicación entre pods. 
|===

NOTE: Para implementaciones de alta disponibilidad, asegúrese de que el puerto UDP 8472 esté abierto entre todos los nodos.  Este puerto permite la comunicación entre pods a través de nodos; bloquearlo interrumpirá la comunicación entre nodos.



== Límites de configuración para implementar ONTAP tools for VMware vSphere

Puede utilizar la siguiente tabla como guía para configurar las ONTAP tools for VMware vSphere.

|===


| *Despliegue* | *Tipo* | *Número de vVols* | *Número de hosts* 


| No HA | Pequeño (S) | ~12 mil | 32 


| No HA | Mediano (M) | ~24K | 64 


| Alta disponibilidad | Pequeño (S) | ~24K | 64 


| Alta disponibilidad | Mediano (M) | ~50k | 128 


| Alta disponibilidad | Grande (L) | ~100k | 256 [NOTA] La cantidad de hosts en la tabla muestra la cantidad total de hosts de varios vCenters. 
|===


== ONTAP tools for VMware vSphere : Adaptador de replicación de almacenamiento (SRA)

La siguiente tabla muestra los números admitidos por instancia de VMware Live Site Recovery mediante ONTAP tools for VMware vSphere.

|===
| *Tamaño de implementación de vCenter* | *Pequeño* | *Medio* 


| Número total de máquinas virtuales configuradas para protección mediante replicación basada en matrices | 2000 | 5000 


| Número total de grupos de protección de replicación basados en matrices | 250 | 250 


| Número total de grupos de protección por plan de recuperación | 50 | 50 


| Número de almacenes de datos replicados | 255 | 255 


| Número de máquinas virtuales | 4000 | 7000 
|===
La siguiente tabla muestra la cantidad de VMware Live Site Recovery y las ONTAP tools for VMware vSphere .

|===


| *Número de instancias de VMware Live Site Recovery* | * Tamaño de implementación de las herramientas ONTAP * 


| Hasta 4 | Pequeño 


| 4 a 8 | Medio 


| Más de 8 | Grande 
|===
Para más información, consulte  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Límites operativos de VMware Live Site Recovery"] .
