---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Debe configurar los intervalos de tiempo de espera de almacenamiento según las configuraciones recomendadas para que el Adaptador de replicación de almacenamiento (SRA) funcione de manera óptima en entornos de gran escalabilidad.' 
---
= Configurar SRA para entornos de gran escalabilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar los intervalos de tiempo de espera de almacenamiento según las configuraciones recomendadas para que el Adaptador de replicación de almacenamiento (SRA) funcione de manera óptima en entornos altamente escalables.



== Configuración del proveedor de almacenamiento

Debe establecer los siguientes valores de tiempo de espera en VMware Live Site Recovery para el entorno escalado:

|===


| *Configuración avanzada* | *Valores de tiempo de espera* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Aumente el valor de la configuración de 900 segundos a 12000 segundos.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Establezca un valor alto (por ejemplo: 99999)

|===
También deberías habilitar la `StorageProvider.autoResignatureMode` opción.

Referirse a https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Cambiar la configuración del proveedor de almacenamiento"] para obtener más información sobre cómo modificar la configuración del proveedor de almacenamiento.



== Configuración de almacenamiento

Cuando llegues a un tiempo de espera, aumenta los valores de `storage.commandTimeout` y `storage.maxConcurrentCommandCnt` a un valor superior.


NOTE: El intervalo de tiempo de espera especificado es el valor máximo. No es necesario esperar a que se alcance el tiempo de espera máximo. La mayoría de los comandos finalizan dentro del intervalo de tiempo de espera máximo establecido.

Referirse a https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Cambiar la configuración de almacenamiento"] para modificar la configuración del proveedor SAN.
