---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Para que VMware Live Site Recovery se comunique con SRA, debe actualizar las credenciales de SRA en el servidor de VMware Live Site Recovery si ha modificado las credenciales. 
---
= Actualizar las credenciales de SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que VMware Live Site Recovery se comunique con SRA, debe actualizar las credenciales de SRA en el servidor de VMware Live Site Recovery si ha modificado las credenciales.

.Antes de empezar
Deberías haber ejecutado los pasos mencionados en el tema.link:../protect/configure-on-srm-appliance.html["Configuración de SRA en el dispositivo VMware Live Site Recovery"] .

.Pasos
. Ejecute los siguientes comandos para eliminar el nombre de usuario y la contraseña de las herramientas ONTAP almacenadas en caché de la carpeta de la máquina VMware Live Site Recovery:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Ejecute el comando Perl para configurar SRA con las nuevas credenciales:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>`Es necesario tener una comilla simple alrededor del valor de la contraseña.
+
Se muestra un mensaje de éxito que confirma que se guardaron las credenciales de almacenamiento.  SRA puede comunicarse con el servidor SRA utilizando la dirección IP, el puerto y las credenciales proporcionados.




