---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Los backends de almacenamiento son sistemas que los hosts ESXi utilizan para el almacenamiento de datos. 
---
= Agregar un backend de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Agregar un backend de almacenamiento le permite incorporar un clúster ONTAP .

*Acerca de esta tarea*

En el caso de configuraciones de múltiples inquilinos donde vCenter actúa como inquilino con un SVM asociado, utilice el Administrador de herramientas de ONTAP para agregar el clúster.  Asocie el backend de almacenamiento con vCenter Server para asignarlo globalmente a la instancia de vCenter Server incorporada.  El inquilino de vCenter debe incorporar las máquinas virtuales de almacenamiento (SVM) deseadas.  Esto permite que un usuario de SVM aprovisione almacenes de datos vVols .  Puede agregar almacenamiento en vCenter usando SVM.

Agregue los backends de almacenamiento local con credenciales de clúster o SVM mediante la interfaz de usuario de las herramientas ONTAP .  Estos backends de almacenamiento están limitados a un único vCenter.  Al utilizar credenciales de clúster localmente, las SVM asociadas se asignan automáticamente al vCenter para administrar vVols o VMFS.  Para la administración de VMFS, incluido SRA, las herramientas ONTAP admiten credenciales SVM sin necesidad de un clúster global.

[role="tabbed-block"]
====
.Uso del Administrador de herramientas de ONTAP
--

NOTE: En una configuración de múltiples inquilinos, puede agregar un clúster de backend de almacenamiento a nivel global y SVM a nivel local para usar las credenciales de usuario de SVM.

.Pasos
. Inicie el Administrador de herramientas de ONTAP desde un navegador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las credenciales de administrador de las ONTAP tools for VMware vSphere que proporcionó durante la implementación.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Agregue el backend de almacenamiento y proporcione la dirección IP del servidor o FQDN, el nombre de usuario y los detalles de la contraseña.
+

NOTE: Se admiten LIF de gestión de direcciones IPv4 e IPv6.



--
.Uso de la interfaz de usuario del cliente vSphere
--

NOTE: Al configurar un backend de almacenamiento a través de la interfaz de usuario del cliente vSphere, es importante tener en cuenta que los almacenes de datos vVols no admiten la adición directa de un usuario SVM.

. Inicie sesión en el cliente vSphere.
. En la página de accesos directos, seleccione *Herramientas de NetApp ONTAP * en la sección de complementos.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Agregue el backend de almacenamiento y proporcione la dirección IP del servidor, el nombre de usuario, la contraseña y los detalles del puerto.
+

NOTE: Para agregar un usuario SVM directamente, puede agregar credenciales basadas en clúster y LIF de administración de direcciones IPv4 e IPv6 o proporcionar credenciales basadas en SVM con un LIF de administración de SVM.



.¿Que sigue?
La lista se actualiza y puedes ver el backend de almacenamiento recientemente agregado en la lista.

--
====