---
permalink: manage/change-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Puede cambiar la contraseña de administrador utilizando el Administrador de herramientas de ONTAP . 
---
= Cambiar la contraseña del administrador de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la contraseña de administrador utilizando el Administrador de herramientas de ONTAP .

.Pasos
. Inicie el Administrador de herramientas de ONTAP desde un navegador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las credenciales de administrador de las ONTAP tools for VMware vSphere que proporcionó durante la implementación.
. Seleccione el ícono de *administrador* en la esquina superior derecha de la pantalla y seleccione *Cambiar contraseña*.
. En la ventana emergente de cambio de contraseña, ingrese la contraseña anterior y los detalles de la nueva contraseña.  La restricción para cambiar la contraseña se muestra en la pantalla de la interfaz de usuario.
. Seleccione *Cambiar* para implementar los cambios.

