---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Si olvidó la contraseña del administrador de herramientas de ONTAP , puede restablecer las credenciales de administrador usando el token generado por la consola de mantenimiento de ONTAP tools for VMware vSphere . 
---
= Restablecer la contraseña del administrador de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si olvidó la contraseña del administrador de herramientas de ONTAP , puede restablecer las credenciales de administrador usando el token generado por la consola de mantenimiento de ONTAP tools for VMware vSphere .

.Pasos
. Inicie el Administrador de herramientas de ONTAP desde un navegador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. En la pantalla de inicio de sesión, seleccione la opción *Restablecer contraseña*.
+
Para restablecer la contraseña del administrador, debe generar el token de restablecimiento utilizando las ONTAP tools for VMware vSphere .

+
.. Desde vCenter Server, abra la consola de mantenimiento
.. Ingrese '2' para seleccionar la opción Configuración del sistema
.. Introduzca '3' para cambiar la contraseña del usuario 'maint'.


. En la ventana emergente de cambio de contraseña, ingrese el token de restablecimiento de contraseña, el nombre de usuario y los detalles de la nueva contraseña.
. Seleccione *Restablecer* para implementar los cambios.  Después de restablecer exitosamente la contraseña, podrá usar la nueva contraseña para iniciar sesión.

